name: compile_prerelease
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  compile_prerelease:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Bass lib
        shell: pwsh
        run: |
          Invoke-WebRequest "www.un4seen.com/files/bass24.zip" -OutFile ".\bass24.zip";
          Expand-Archive -Path ".\bass24.zip" -DestinationPath ".\base24\";
          Remove-Item -Path ".\bass24.zip" -Force
          Copy-Item -Path ".\base24\x64\bass.dll" -Destination ".\src\Lib\bass.dll" -Force;

      - name: Download dependencies
        shell: pwsh
        run: |
          $cwd = (Get-Item .).FullName;
          Invoke-WebRequest "https://github.com/joshuacc/ahkpm/releases/download/0.7.0/ahkpm-0.7.0.msi" -OutFile "$cwd\ahkpm.msi";
          Start-Process "MSIEXEC" -ArgumentList "/a `"$cwd\ahkpm.msi`" /qn TARGETDIR=`"$cwd\ahkpmDir`"" -Wait -NoNewWindow
          Start-Process "$cwd\ahkpmDir\ahkpm\ahkpm.exe" -ArgumentList "install" -WorkingDirectory "$cwd" -Wait -NoNewWindow

      - name: Compile MicMute
        uses: nekocodeX/GitHub-Action-Ahk2Exe@v1.1.0
        with:
          in: '.\src\MicMute.ahk'
          out: '.\MicMute.exe'

      - name: Calculate file hash
        shell: pwsh
        run: (Get-FileHash '.\MicMute.exe').Hash  | Tee-Object -FilePath  .\MicMute.sha256;
      
      - uses: actions/upload-artifact@v3
        with:
          name: MicMute
          path: ./MicMute.*

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest_commit"
          prerelease: true
          title: "Development Build"
          files: |
            MicMute.exe
            MicMute.sha256
