name: compile_prerelease
on:
  workflow_dispatch:
jobs:
  compile:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: Recreate release
        id: recreate_release
        uses: GongT/actions-recreate-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest_commit
          release_name: Build at latest commit
          draft: false
          prerelease: true
      
      - name: Build artifacts
        id: build_artifacts
        shell: pwsh
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser -Force;
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
          scoop bucket add utils https://github.com/SaifAqqad/utils.git;
          scoop install utils/autohotkey;
          echo "Running Ahk2Exe";
          & "$(scoop prefix autohotkey)\Compiler\Ahk2Exe.exe" /in ".\src\MicMute.ahk" /out "MicMute.exe" /icon ".\src\MicMute.ico" | more
          echo "MicMute compiled: $LASTEXITCODE"
          & "$(scoop prefix autohotkey)\Compiler\Ahk2Exe.exe" /in ".\src\updater\updater.ahk" /out "updater.exe" /icon ".\src\MicMute.ico" | more
          echo "updater compiled: $LASTEXITCODE"
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.exe"
          tag: latest_commit
          overwrite: true
          file_glob: true
